version: "3"

services:
  sslocal:
    image: lqhuang/shadowsocks-rust:sslocal-v1.8.13-v2ray-plugin-v1.3.1
    container_name: ss-local
    hostname: ss-local
    restart: always
    ports:
      - 1080:1080/tcp
      - 1080:1080/udp
      - 8118:8118
    volumes:
      - /dev/urandom:/dev/random
      - ./config.json:/etc/shadowsocks-libev/config.json
    network_mode: "bridge"
