# check=error=true

FROM ghcr.io/sagernet/sing-box:v1.12.9 AS sb-dist

FROM docker.io/lqhuang/alpine-s6:3.22

ARG ALPINE_OC_VERSION

COPY --from=sb-dist /usr/local/bin/sing-box /usr/bin/sing-box

RUN apk add --no-cache openconnect=9.12-r1 \
    && apk cache clean

COPY ./rootfs /

VOLUME /etc/openconnect

ENTRYPOINT ["/init"]

CMD ["openconnect", "--help"]
# "--config=/etc/openconnect/openconnect.conf"
