name: Build docker for Clash Core (Open Source)

on:
  push:
    paths:
      - docker/clash/.core.env
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CONTEXT_ROOT: docker/clash

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Load build args for Dockerfile
        run: |
          source ${{ env.CONTEXT_ROOT }}/.core.env
          echo "YACD_VERSION=$YACD_VERSION" >> $GITHUB_ENV
          echo "CLASH_CORE_VERSION=$CLASH_CORE_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.4.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT_ROOT }}
          file: ${{ env.CONTEXT_ROOT }}/clash-core.Dockerfile
          build-args: |
            YACD_VERSION=${{ env.YACD_VERSION }}
            CLASH_CORE_VERSION=${{ env.CLASH_CORE_VERSION }}
          push: true
          provenance: mode=min,inline-only=true
          tags: |
            lqhuang/clash:${{ env.CLASH_CORE_VERSION }}
            ghcr.io/lqhuang/clash:${{ env.CLASH_CORE_VERSION }}
