name: Build docker for caddy

on:
  push:
    paths:
      - docker/caddy/.env
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CONTEXT_ROOT: docker/caddy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Load build args for Dockerfile
        run: |
          echo "Sourcing ${{ env.CONTEXT_ROOT }}/.env"
          source ${{ env.CONTEXT_ROOT }}/.env
          echo "Loaded envs: CADDY_VERSION=$CADDY_VERSION"
          echo "CADDY_VERSION=$CADDY_VERSION" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.16.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT_ROOT }}
          file: ${{ env.CONTEXT_ROOT }}/Dockerfile
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
          push: true
          provenance: mode=min,inline-only=true
          tags: |
            lqhuang/caddy:${{ env.CADDY_VERSION }}
            ghcr.io/lqhuang/caddy:${{ env.CADDY_VERSION }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/caddy:cache
          cache-to: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/caddy:cache,mode=max
