name: Build docker for naiveproxy client

on:
  push:
    paths:
      - docker/naiveproxy/.env
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CONTEXT_ROOT: docker/naiveproxy

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Load build args for Dockerfile
        run: |
          source ${{ env.CONTEXT_ROOT }}/.env
          echo "NAIVEPROXY_VERSION=$NAIVEPROXY_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.1.0
        with:
          platforms: linux/amd64 # ,linux/arm64
          context: ${{ env.CONTEXT_ROOT }}
          file: ${{ env.CONTEXT_ROOT }}/Dockerfile
          build-args: |
            NAIVEPROXY_VERSION=${{ env.NAIVEPROXY_VERSION }}
          push: true
          provenance: mode=min,inline-only=true
          tags: |
            lqhuang/naiveproxy:${{ env.NAIVEPROXY_VERSION }}
            lqhuang/naiveproxy:latest
            ghcr.io/lqhuang/naiveproxy:${{ env.NAIVEPROXY_VERSION }}
            ghcr.io/lqhuang/naiveproxy:latest
